//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class PatientSearch
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private PatientSearch() : base("LightSwitchApplication:PatientSearch")
        {
            global::LightSwitchApplication.PatientSearch.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static PatientSearch CreateInstance()
        {
            return new global::LightSwitchApplication.PatientSearch(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientSearch_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientSearch_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientSearch_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientSearch_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientSearch_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientSearch_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientSearch_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Patients_SelectionChanged();

        partial void Patients_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Loaded(bool succeeded);

        partial void CurrentPatients_Changed();

        partial void CurrentPatients1_SelectionChanged();

        partial void CurrentPatients1_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentPatients1_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Patients visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Patient> Patients
        {
            get
            {
                return global::LightSwitchApplication.PatientSearch.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties.Patients);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool CurrentPatients
        {
            get 
            {
                return global::LightSwitchApplication.PatientSearch.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties.CurrentPatients);
            }
            set
            {
                global::LightSwitchApplication.PatientSearch.DetailsClass.SetValue(this, global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties.CurrentPatients, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentPatients_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the CurrentPatients1 visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Patient> CurrentPatients1
        {
            get
            {
                return global::LightSwitchApplication.PatientSearch.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties.CurrentPatients1);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentPatients1_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySet, global::LightSwitchApplication.PatientSearch.DetailsClass.CommandSet, global::LightSwitchApplication.PatientSearch.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties.Patients;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass>.Entry
                __PatientSearchEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass>.Entry(
                    global::LightSwitchApplication.PatientSearch.DetailsClass.__PatientSearch_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.PatientSearch.DetailsClass.__PatientSearch_InvokeSavingEvent,
                    global::LightSwitchApplication.PatientSearch.DetailsClass.__PatientSearch_InvokeSavedEvent,
                    global::LightSwitchApplication.PatientSearch.DetailsClass.__PatientSearch_InvokeClosingEvent,
                    global::LightSwitchApplication.PatientSearch.DetailsClass.__PatientSearch_InvokeCreated,
                    global::LightSwitchApplication.PatientSearch.DetailsClass.__PatientSearch_InvokeActivated,
                    global::LightSwitchApplication.PatientSearch.DetailsClass.__PatientSearch_InvokeSaveErrorEvent);
            private static void __PatientSearch_InvokeInitializeDataWorkspace(global::LightSwitchApplication.PatientSearch s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.PatientSearch_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __PatientSearch_InvokeSavingEvent(global::LightSwitchApplication.PatientSearch s)
            {
                bool handled = false;
                s.PatientSearch_Saving(ref handled);
                return handled;
            }
            private static void __PatientSearch_InvokeSavedEvent(global::LightSwitchApplication.PatientSearch s)
            {
                s.PatientSearch_Saved();
            }
            private static bool __PatientSearch_InvokeClosingEvent(global::LightSwitchApplication.PatientSearch s)
            {
                bool cancel = false;
                s.PatientSearch_Closing(ref cancel);
                return cancel;
            }
            private static void __PatientSearch_InvokeCreated(global::LightSwitchApplication.PatientSearch s)
            {
                s.PatientSearch_Created();
            }
            private static void __PatientSearch_InvokeActivated(global::LightSwitchApplication.PatientSearch s)
            {
                s.PatientSearch_Activated();
            }
            private static bool __PatientSearch_InvokeSaveErrorEvent(global::LightSwitchApplication.PatientSearch s, global::System.Exception ex)
            {
                bool handled = false;
                s.PatientSearch_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.PatientSearch.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.PatientSearch.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable PatientsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Patients;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CurrentPatients1Query(global::System.Nullable<bool> SelectOnlyCurrent)
            {
                return this.Screen.DataWorkspace.ApplicationData.CurrentPatients(SelectOnlyCurrent);
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>.Data _Patients;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, bool>.Data _CurrentPatients;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>.Data _CurrentPatients1;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient> Patients
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>)base.GetItem(global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties.Patients);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, bool> CurrentPatients
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, bool>)base.GetItem(global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties.CurrentPatients);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient> CurrentPatients1
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>)base.GetItem(global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties.CurrentPatients1);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>.Entry
                    Patients = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>.Entry(
                        "Patients",
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._Patients_Stub,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._Patients_Validate,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._Patients_CreateQuery,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._Patients_SelectionChanged,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._Patients_OnCollectionChanged,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._Patients_OnLoaded);
                private static void _Patients_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientSearch.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>.Data> c, global::LightSwitchApplication.PatientSearch.DetailsClass d, object sf)
                {
                    c(d, ref d._Patients, sf);
                }
                private static void _Patients_Validate(global::LightSwitchApplication.PatientSearch s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Patients_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Patients_CreateQuery(global::LightSwitchApplication.PatientSearch.DetailsClass d, object[] args)
                {
                    return d.PatientsQuery();
                }
                private static void _Patients_SelectionChanged(global::LightSwitchApplication.PatientSearch s)
                {
                    s.Patients_SelectionChanged();
                }
                private static void _Patients_OnCollectionChanged(global::LightSwitchApplication.PatientSearch s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Patients_Changed(e);
                }
                private static void _Patients_OnLoaded(global::LightSwitchApplication.PatientSearch s, bool succeeded)
                {
                    s.Patients_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, bool>.Entry
                    CurrentPatients = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, bool>.Entry(
                        "CurrentPatients",
                        false,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients_Stub,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients_Validate,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients_OnValueChanged);
                private static void _CurrentPatients_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientSearch.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, bool>.Data> c, global::LightSwitchApplication.PatientSearch.DetailsClass d, object sf)
                {
                    c(d, ref d._CurrentPatients, sf);
                }
                private static void _CurrentPatients_Validate(global::LightSwitchApplication.PatientSearch s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CurrentPatients_Validate(r);
                }
                private static void _CurrentPatients_OnValueChanged(global::LightSwitchApplication.PatientSearch s)
                {
                    s.CurrentPatients_Changed();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>.Entry
                    CurrentPatients1 = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>.Entry(
                        "CurrentPatients1",
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients1_Stub,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients1_Validate,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients1_CreateQuery,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients1_SelectionChanged,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients1_OnCollectionChanged,
                        global::LightSwitchApplication.PatientSearch.DetailsClass.PropertySetProperties._CurrentPatients1_OnLoaded);
                private static void _CurrentPatients1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientSearch.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientSearch, global::LightSwitchApplication.PatientSearch.DetailsClass, global::LightSwitchApplication.Patient>.Data> c, global::LightSwitchApplication.PatientSearch.DetailsClass d, object sf)
                {
                    c(d, ref d._CurrentPatients1, sf);
                }
                private static void _CurrentPatients1_Validate(global::LightSwitchApplication.PatientSearch s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CurrentPatients1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _CurrentPatients1_CreateQuery(global::LightSwitchApplication.PatientSearch.DetailsClass d, object[] args)
                {
                    return d.CurrentPatients1Query((global::System.Nullable<bool>)args[0]);
                }
                private static void _CurrentPatients1_SelectionChanged(global::LightSwitchApplication.PatientSearch s)
                {
                    s.CurrentPatients1_SelectionChanged();
                }
                private static void _CurrentPatients1_OnCollectionChanged(global::LightSwitchApplication.PatientSearch s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.CurrentPatients1_Changed(e);
                }
                private static void _CurrentPatients1_OnLoaded(global::LightSwitchApplication.PatientSearch s, bool succeeded)
                {
                    s.CurrentPatients1_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class PatientDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private PatientDetail(int PatientId) : base("LightSwitchApplication:PatientDetail")
        {
                this.PatientId = PatientId;
            global::LightSwitchApplication.PatientDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static PatientDetail CreateInstance(int PatientId)
        {
            return new global::LightSwitchApplication.PatientDetail(
                        PatientId
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Patient_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Loaded(bool succeeded);

        partial void PatientId_Changed();

        partial void SpecificLabsCollection_SelectionChanged();

        partial void SpecificLabsCollection_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SpecificLabsCollection_Loaded(bool succeeded);

        partial void Treatments_SelectionChanged();

        partial void Treatments_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Treatments_Loaded(bool succeeded);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Patient Patient
        {
            get
            {
                return global::LightSwitchApplication.PatientDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.Patient);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PatientId
        {
            get 
            {
                return global::LightSwitchApplication.PatientDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.PatientId);
            }
            set
            {
                global::LightSwitchApplication.PatientDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.PatientId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the SpecificLabsCollection visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.SpecificLabs> SpecificLabsCollection
        {
            get
            {
                return global::LightSwitchApplication.PatientDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.SpecificLabsCollection);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SpecificLabsCollection_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Treatments visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Treatment> Treatments
        {
            get
            {
                return global::LightSwitchApplication.PatientDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.Treatments);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Treatments_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySet, global::LightSwitchApplication.PatientDetail.DetailsClass.CommandSet, global::LightSwitchApplication.PatientDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.Patient;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>.Entry
                __PatientDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeCreated,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeActivated,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeSaveErrorEvent);
            private static void __PatientDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.PatientDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.PatientDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __PatientDetail_InvokeSavingEvent(global::LightSwitchApplication.PatientDetail s)
            {
                bool handled = false;
                s.PatientDetail_Saving(ref handled);
                return handled;
            }
            private static void __PatientDetail_InvokeSavedEvent(global::LightSwitchApplication.PatientDetail s)
            {
                s.PatientDetail_Saved();
            }
            private static bool __PatientDetail_InvokeClosingEvent(global::LightSwitchApplication.PatientDetail s)
            {
                bool cancel = false;
                s.PatientDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __PatientDetail_InvokeCreated(global::LightSwitchApplication.PatientDetail s)
            {
                s.PatientDetail_Created();
            }
            private static void __PatientDetail_InvokeActivated(global::LightSwitchApplication.PatientDetail s)
            {
                s.PatientDetail_Activated();
            }
            private static bool __PatientDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.PatientDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.PatientDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.PatientDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.PatientDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable SpecificLabsCollectionQuery()
            {
                if (this.Screen.Patient == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.SpecificLabs> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.SpecificLabs>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Patient.Details.Properties.SpecificLabsCollection).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable TreatmentsQuery()
            {
                if (this.Screen.Patient == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Treatment> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Treatment>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Patient.Details.Properties.Treatments).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>.Data _Patient;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>.Data _PatientId;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Data _SpecificLabsCollection;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Treatment>.Data _Treatments;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient> Patient
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>)base.GetItem(global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.Patient);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int> PatientId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>)base.GetItem(global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.PatientId);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs> SpecificLabsCollection
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>)base.GetItem(global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.SpecificLabsCollection);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Treatment> Treatments
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Treatment>)base.GetItem(global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.Treatments);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>.Entry
                    Patient = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>.Entry(
                        "Patient",
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_Stub,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_Validate,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_CreateQuery,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_OnValueChanged,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_OnLoaded);
                private static void _Patient_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>.Data> c, global::LightSwitchApplication.PatientDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Patient, sf);
                }
                private static void _Patient_Validate(global::LightSwitchApplication.PatientDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Patient_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Patient_CreateQuery(global::LightSwitchApplication.PatientDetail.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _Patient_OnValueChanged(global::LightSwitchApplication.PatientDetail s)
                {
                    s.Patient_Changed();
                }

                private static void _Patient_OnLoaded(global::LightSwitchApplication.PatientDetail s, bool succeeded)
                {
                    s.Patient_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>.Entry
                    PatientId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>.Entry(
                        "PatientId",
                        false,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._PatientId_Stub,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._PatientId_Validate,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._PatientId_OnValueChanged);
                private static void _PatientId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.PatientDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._PatientId, sf);
                }
                private static void _PatientId_Validate(global::LightSwitchApplication.PatientDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.PatientId_Validate(r);
                }
                private static void _PatientId_OnValueChanged(global::LightSwitchApplication.PatientDetail s)
                {
                    s.PatientId_Changed();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Entry
                    SpecificLabsCollection = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Entry(
                        "SpecificLabsCollection",
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._SpecificLabsCollection_Stub,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._SpecificLabsCollection_Validate,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._SpecificLabsCollection_CreateQuery,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._SpecificLabsCollection_SelectionChanged,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._SpecificLabsCollection_OnCollectionChanged,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._SpecificLabsCollection_OnLoaded);
                private static void _SpecificLabsCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Data> c, global::LightSwitchApplication.PatientDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._SpecificLabsCollection, sf);
                }
                private static void _SpecificLabsCollection_Validate(global::LightSwitchApplication.PatientDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.SpecificLabsCollection_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _SpecificLabsCollection_CreateQuery(global::LightSwitchApplication.PatientDetail.DetailsClass d, object[] args)
                {
                    return d.SpecificLabsCollectionQuery();
                }
                private static void _SpecificLabsCollection_SelectionChanged(global::LightSwitchApplication.PatientDetail s)
                {
                    s.SpecificLabsCollection_SelectionChanged();
                }
                private static void _SpecificLabsCollection_OnCollectionChanged(global::LightSwitchApplication.PatientDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.SpecificLabsCollection_Changed(e);
                }
                private static void _SpecificLabsCollection_OnLoaded(global::LightSwitchApplication.PatientDetail s, bool succeeded)
                {
                    s.SpecificLabsCollection_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Treatment>.Entry
                    Treatments = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Treatment>.Entry(
                        "Treatments",
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Treatments_Stub,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Treatments_Validate,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Treatments_CreateQuery,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Treatments_SelectionChanged,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Treatments_OnCollectionChanged,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Treatments_OnLoaded);
                private static void _Treatments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Treatment>.Data> c, global::LightSwitchApplication.PatientDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Treatments, sf);
                }
                private static void _Treatments_Validate(global::LightSwitchApplication.PatientDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Treatments_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Treatments_CreateQuery(global::LightSwitchApplication.PatientDetail.DetailsClass d, object[] args)
                {
                    return d.TreatmentsQuery();
                }
                private static void _Treatments_SelectionChanged(global::LightSwitchApplication.PatientDetail s)
                {
                    s.Treatments_SelectionChanged();
                }
                private static void _Treatments_OnCollectionChanged(global::LightSwitchApplication.PatientDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Treatments_Changed(e);
                }
                private static void _Treatments_OnLoaded(global::LightSwitchApplication.PatientDetail s, bool succeeded)
                {
                    s.Treatments_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class TreatmentDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private TreatmentDetail(int TreatmentId) : base("LightSwitchApplication:TreatmentDetail")
        {
                this.TreatmentId = TreatmentId;
            global::LightSwitchApplication.TreatmentDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static TreatmentDetail CreateInstance(int TreatmentId)
        {
            return new global::LightSwitchApplication.TreatmentDetail(
                        TreatmentId
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TreatmentDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TreatmentDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TreatmentDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TreatmentDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TreatmentDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TreatmentDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TreatmentDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Treatment_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Treatment_Loaded(bool succeeded);

        partial void TreatmentId_Changed();

        partial void SpecificLabsSet_SelectionChanged();

        partial void SpecificLabsSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SpecificLabsSet_Loaded(bool succeeded);

        partial void SpecificLabsTreatmentId_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Treatment Treatment
        {
            get
            {
                return global::LightSwitchApplication.TreatmentDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.Treatment);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Treatment_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TreatmentId
        {
            get 
            {
                return global::LightSwitchApplication.TreatmentDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.TreatmentId);
            }
            set
            {
                global::LightSwitchApplication.TreatmentDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.TreatmentId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TreatmentId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the SpecificLabsSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.SpecificLabs> SpecificLabsSet
        {
            get
            {
                return global::LightSwitchApplication.TreatmentDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.SpecificLabsSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SpecificLabsSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> SpecificLabsTreatmentId
        {
            get 
            {
                return global::LightSwitchApplication.TreatmentDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.SpecificLabsTreatmentId);
            }
            set
            {
                global::LightSwitchApplication.TreatmentDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.SpecificLabsTreatmentId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SpecificLabsTreatmentId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySet, global::LightSwitchApplication.TreatmentDetail.DetailsClass.CommandSet, global::LightSwitchApplication.TreatmentDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.Treatment;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass>.Entry
                __TreatmentDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.TreatmentDetail.DetailsClass.__TreatmentDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.TreatmentDetail.DetailsClass.__TreatmentDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.TreatmentDetail.DetailsClass.__TreatmentDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.TreatmentDetail.DetailsClass.__TreatmentDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.TreatmentDetail.DetailsClass.__TreatmentDetail_InvokeCreated,
                    global::LightSwitchApplication.TreatmentDetail.DetailsClass.__TreatmentDetail_InvokeActivated,
                    global::LightSwitchApplication.TreatmentDetail.DetailsClass.__TreatmentDetail_InvokeSaveErrorEvent);
            private static void __TreatmentDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.TreatmentDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.TreatmentDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __TreatmentDetail_InvokeSavingEvent(global::LightSwitchApplication.TreatmentDetail s)
            {
                bool handled = false;
                s.TreatmentDetail_Saving(ref handled);
                return handled;
            }
            private static void __TreatmentDetail_InvokeSavedEvent(global::LightSwitchApplication.TreatmentDetail s)
            {
                s.TreatmentDetail_Saved();
            }
            private static bool __TreatmentDetail_InvokeClosingEvent(global::LightSwitchApplication.TreatmentDetail s)
            {
                bool cancel = false;
                s.TreatmentDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __TreatmentDetail_InvokeCreated(global::LightSwitchApplication.TreatmentDetail s)
            {
                s.TreatmentDetail_Created();
            }
            private static void __TreatmentDetail_InvokeActivated(global::LightSwitchApplication.TreatmentDetail s)
            {
                s.TreatmentDetail_Activated();
            }
            private static bool __TreatmentDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.TreatmentDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.TreatmentDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.TreatmentDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.TreatmentDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable SpecificLabsSetQuery(global::System.Nullable<int> TreatmentId)
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    this.Screen.DataWorkspace.ApplicationData.LabsBetweenTreatments(TreatmentId),
                    "Patient");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.Treatment>.Data _Treatment;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, int>.Data _TreatmentId;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Data _SpecificLabsSet;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::System.Nullable<int>>.Data _SpecificLabsTreatmentId;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.Treatment> Treatment
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.Treatment>)base.GetItem(global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.Treatment);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, int> TreatmentId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, int>)base.GetItem(global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.TreatmentId);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs> SpecificLabsSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>)base.GetItem(global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.SpecificLabsSet);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::System.Nullable<int>> SpecificLabsTreatmentId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::System.Nullable<int>>)base.GetItem(global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties.SpecificLabsTreatmentId);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.Treatment>.Entry
                    Treatment = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.Treatment>.Entry(
                        "Treatment",
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._Treatment_Stub,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._Treatment_Validate,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._Treatment_CreateQuery,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._Treatment_OnValueChanged,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._Treatment_OnLoaded);
                private static void _Treatment_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.Treatment>.Data> c, global::LightSwitchApplication.TreatmentDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Treatment, sf);
                }
                private static void _Treatment_Validate(global::LightSwitchApplication.TreatmentDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Treatment_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Treatment_CreateQuery(global::LightSwitchApplication.TreatmentDetail.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _Treatment_OnValueChanged(global::LightSwitchApplication.TreatmentDetail s)
                {
                    s.Treatment_Changed();
                }

                private static void _Treatment_OnLoaded(global::LightSwitchApplication.TreatmentDetail s, bool succeeded)
                {
                    s.Treatment_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, int>.Entry
                    TreatmentId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, int>.Entry(
                        "TreatmentId",
                        false,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._TreatmentId_Stub,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._TreatmentId_Validate,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._TreatmentId_OnValueChanged);
                private static void _TreatmentId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.TreatmentDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._TreatmentId, sf);
                }
                private static void _TreatmentId_Validate(global::LightSwitchApplication.TreatmentDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.TreatmentId_Validate(r);
                }
                private static void _TreatmentId_OnValueChanged(global::LightSwitchApplication.TreatmentDetail s)
                {
                    s.TreatmentId_Changed();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Entry
                    SpecificLabsSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Entry(
                        "SpecificLabsSet",
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsSet_Stub,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsSet_Validate,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsSet_CreateQuery,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsSet_SelectionChanged,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsSet_OnCollectionChanged,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsSet_OnLoaded);
                private static void _SpecificLabsSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Data> c, global::LightSwitchApplication.TreatmentDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._SpecificLabsSet, sf);
                }
                private static void _SpecificLabsSet_Validate(global::LightSwitchApplication.TreatmentDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.SpecificLabsSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _SpecificLabsSet_CreateQuery(global::LightSwitchApplication.TreatmentDetail.DetailsClass d, object[] args)
                {
                    return d.SpecificLabsSetQuery((global::System.Nullable<int>)args[0]);
                }
                private static void _SpecificLabsSet_SelectionChanged(global::LightSwitchApplication.TreatmentDetail s)
                {
                    s.SpecificLabsSet_SelectionChanged();
                }
                private static void _SpecificLabsSet_OnCollectionChanged(global::LightSwitchApplication.TreatmentDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.SpecificLabsSet_Changed(e);
                }
                private static void _SpecificLabsSet_OnLoaded(global::LightSwitchApplication.TreatmentDetail s, bool succeeded)
                {
                    s.SpecificLabsSet_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::System.Nullable<int>>.Entry
                    SpecificLabsTreatmentId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::System.Nullable<int>>.Entry(
                        "SpecificLabsTreatmentId",
                        false,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsTreatmentId_Stub,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsTreatmentId_Validate,
                        global::LightSwitchApplication.TreatmentDetail.DetailsClass.PropertySetProperties._SpecificLabsTreatmentId_OnValueChanged);
                private static void _SpecificLabsTreatmentId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.TreatmentDetail, global::LightSwitchApplication.TreatmentDetail.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.TreatmentDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._SpecificLabsTreatmentId, sf);
                }
                private static void _SpecificLabsTreatmentId_Validate(global::LightSwitchApplication.TreatmentDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.SpecificLabsTreatmentId_Validate(r);
                }
                private static void _SpecificLabsTreatmentId_OnValueChanged(global::LightSwitchApplication.TreatmentDetail s)
                {
                    s.SpecificLabsTreatmentId_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
