

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Patient : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Patient entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Patient()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Patient(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Patient> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Patient.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Patient.DetailsClass.GetValue(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Patient.DetailsClass.SetValue(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FirstName
        {
            get
            {
                return global::LightSwitchApplication.Patient.DetailsClass.GetValue(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.FirstName);
            }
            set
            {
                global::LightSwitchApplication.Patient.DetailsClass.SetValue(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.FirstName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastName
        {
            get
            {
                return global::LightSwitchApplication.Patient.DetailsClass.GetValue(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.LastName);
            }
            set
            {
                global::LightSwitchApplication.Patient.DetailsClass.SetValue(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.LastName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.SpecificLabs> SpecificLabsCollection
        {
            get
            {
                return global::LightSwitchApplication.Patient.DetailsClass.GetValue(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.SpecificLabsCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.SpecificLabs> SpecificLabsCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.Patient.DetailsClass.GetQuery(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.SpecificLabsCollection);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Treatment> Treatments
        {
            get
            {
                return global::LightSwitchApplication.Patient.DetailsClass.GetValue(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.Treatments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Treatment> TreatmentsQuery
        {
            get
            {
                return global::LightSwitchApplication.Patient.DetailsClass.GetQuery(this, global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.Treatments);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Patient,
                global::LightSwitchApplication.Patient.DetailsClass,
                global::LightSwitchApplication.Patient.DetailsClass.IImplementation,
                global::LightSwitchApplication.Patient.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass>.Entry
                __PatientEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass>.Entry(
                    global::LightSwitchApplication.Patient.DetailsClass.__Patient_CreateNew,
                    global::LightSwitchApplication.Patient.DetailsClass.__Patient_Created,
                    global::LightSwitchApplication.Patient.DetailsClass.__Patient_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Patient __Patient_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Patient> es)
            {
                return new global::LightSwitchApplication.Patient(es);
            }
            private static void __Patient_Created(global::LightSwitchApplication.Patient e)
            {
                e.Patient_Created();
            }
            private static bool __Patient_AllowSaveWithErrors(global::LightSwitchApplication.Patient e)
            {
                bool result = false;
                e.Patient_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Patient.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string> FirstName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.FirstName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string> LastName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.LastName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.SpecificLabs> SpecificLabsCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.SpecificLabsCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.SpecificLabs>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.Treatment> Treatments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.Treatments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.Treatment>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string FirstName { get; set; }
                new string LastName { get; set; }
                new global::System.Collections.IEnumerable SpecificLabsCollection { get; }
                new global::System.Collections.IEnumerable Treatments { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Patient.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, int>.Data> c, global::LightSwitchApplication.Patient.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Patient e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Patient e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Patient.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Patient.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Patient e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>.Entry
                    FirstName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>.Entry(
                        "FirstName",
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._FirstName_Stub,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._FirstName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._FirstName_Validate,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._FirstName_GetImplementationValue,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._FirstName_SetImplementationValue,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._FirstName_OnValueChanged);
                private static void _FirstName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Patient.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>.Data> c, global::LightSwitchApplication.Patient.DetailsClass d, object sf)
                {
                    c(d, ref d._FirstName, sf);
                }
                private static bool _FirstName_ComputeIsReadOnly(global::LightSwitchApplication.Patient e)
                {
                    bool result = false;
                    e.FirstName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FirstName_Validate(global::LightSwitchApplication.Patient e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FirstName_Validate(r);
                }
                private static string _FirstName_GetImplementationValue(global::LightSwitchApplication.Patient.DetailsClass d)
                {
                    return d.ImplementationEntity.FirstName;
                }
                private static void _FirstName_SetImplementationValue(global::LightSwitchApplication.Patient.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FirstName = v;
                }
                private static void _FirstName_OnValueChanged(global::LightSwitchApplication.Patient e)
                {
                    e.FirstName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>.Entry
                    LastName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>.Entry(
                        "LastName",
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._LastName_Stub,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._LastName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._LastName_Validate,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._LastName_GetImplementationValue,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._LastName_SetImplementationValue,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._LastName_OnValueChanged);
                private static void _LastName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Patient.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>.Data> c, global::LightSwitchApplication.Patient.DetailsClass d, object sf)
                {
                    c(d, ref d._LastName, sf);
                }
                private static bool _LastName_ComputeIsReadOnly(global::LightSwitchApplication.Patient e)
                {
                    bool result = false;
                    e.LastName_IsReadOnly(ref result);
                    return result;
                }
                private static void _LastName_Validate(global::LightSwitchApplication.Patient e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LastName_Validate(r);
                }
                private static string _LastName_GetImplementationValue(global::LightSwitchApplication.Patient.DetailsClass d)
                {
                    return d.ImplementationEntity.LastName;
                }
                private static void _LastName_SetImplementationValue(global::LightSwitchApplication.Patient.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LastName = v;
                }
                private static void _LastName_OnValueChanged(global::LightSwitchApplication.Patient e)
                {
                    e.LastName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Entry
                    SpecificLabsCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Entry(
                        "SpecificLabsCollection",
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._SpecificLabsCollection_Stub,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._SpecificLabsCollection_GetReferencedEntities,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._SpecificLabsCollection_GetEntityCollection);
                private static void _SpecificLabsCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Patient.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Data> c, global::LightSwitchApplication.Patient.DetailsClass d, object sf)
                {
                    c(d, ref d._SpecificLabsCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.SpecificLabs> _SpecificLabsCollection_GetReferencedEntities(global::LightSwitchApplication.Patient.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass>(global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.SpecificLabsCollection, ref d._SpecificLabsCollection);
                }
                private static global::System.Collections.IEnumerable _SpecificLabsCollection_GetEntityCollection(global::LightSwitchApplication.Patient.DetailsClass d)
                {
                    return d.ImplementationEntity.SpecificLabsCollection;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.Treatment>.Entry
                    Treatments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.Treatment>.Entry(
                        "Treatments",
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Treatments_Stub,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Treatments_GetReferencedEntities,
                        global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties._Treatments_GetEntityCollection);
                private static void _Treatments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Patient.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.Treatment>.Data> c, global::LightSwitchApplication.Patient.DetailsClass d, object sf)
                {
                    c(d, ref d._Treatments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Treatment> _Treatments_GetReferencedEntities(global::LightSwitchApplication.Patient.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Treatment, global::LightSwitchApplication.Treatment.DetailsClass>(global::LightSwitchApplication.Patient.DetailsClass.PropertySetProperties.Treatments, ref d._Treatments);
                }
                private static global::System.Collections.IEnumerable _Treatments_GetEntityCollection(global::LightSwitchApplication.Patient.DetailsClass d)
                {
                    return d.ImplementationEntity.Treatments;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>.Data _FirstName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, string>.Data _LastName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.SpecificLabs>.Data _SpecificLabsCollection;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass, global::LightSwitchApplication.Treatment>.Data _Treatments;
            
        }
    
        #endregion
    }
    
    #endregion
}
