

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class SpecificLabs : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the SpecificLabs entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SpecificLabs()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SpecificLabs(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SpecificLabs> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.SpecificLabs.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SpecificLabs_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SpecificLabs_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.SpecificLabs.DetailsClass.GetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.SpecificLabs.DetailsClass.SetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateLabIssued
        {
            get
            {
                return global::LightSwitchApplication.SpecificLabs.DetailsClass.GetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.DateLabIssued);
            }
            set
            {
                global::LightSwitchApplication.SpecificLabs.DetailsClass.SetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.DateLabIssued, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateLabIssued_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateLabIssued_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateLabIssued_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double ViralLoad
        {
            get
            {
                return global::LightSwitchApplication.SpecificLabs.DetailsClass.GetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.ViralLoad);
            }
            set
            {
                global::LightSwitchApplication.SpecificLabs.DetailsClass.SetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.ViralLoad, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ViralLoad_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ViralLoad_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ViralLoad_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal WhiteBloodCellCount
        {
            get
            {
                return global::LightSwitchApplication.SpecificLabs.DetailsClass.GetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.WhiteBloodCellCount);
            }
            set
            {
                global::LightSwitchApplication.SpecificLabs.DetailsClass.SetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.WhiteBloodCellCount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WhiteBloodCellCount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WhiteBloodCellCount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WhiteBloodCellCount_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int NumberOfFingers
        {
            get
            {
                return global::LightSwitchApplication.SpecificLabs.DetailsClass.GetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.NumberOfFingers);
            }
            set
            {
                global::LightSwitchApplication.SpecificLabs.DetailsClass.SetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.NumberOfFingers, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NumberOfFingers_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NumberOfFingers_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NumberOfFingers_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Patient Patient
        {
            get
            {
                return global::LightSwitchApplication.SpecificLabs.DetailsClass.GetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Patient);
            }
            set
            {
                global::LightSwitchApplication.SpecificLabs.DetailsClass.SetValue(this, global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Patient, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.SpecificLabs,
                global::LightSwitchApplication.SpecificLabs.DetailsClass,
                global::LightSwitchApplication.SpecificLabs.DetailsClass.IImplementation,
                global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass>.Entry
                __SpecificLabsEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass>.Entry(
                    global::LightSwitchApplication.SpecificLabs.DetailsClass.__SpecificLabs_CreateNew,
                    global::LightSwitchApplication.SpecificLabs.DetailsClass.__SpecificLabs_Created,
                    global::LightSwitchApplication.SpecificLabs.DetailsClass.__SpecificLabs_AllowSaveWithErrors);
            private static global::LightSwitchApplication.SpecificLabs __SpecificLabs_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SpecificLabs> es)
            {
                return new global::LightSwitchApplication.SpecificLabs(es);
            }
            private static void __SpecificLabs_Created(global::LightSwitchApplication.SpecificLabs e)
            {
                e.SpecificLabs_Created();
            }
            private static bool __SpecificLabs_AllowSaveWithErrors(global::LightSwitchApplication.SpecificLabs e)
            {
                bool result = false;
                e.SpecificLabs_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::System.DateTime> DateLabIssued
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.DateLabIssued) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, double> ViralLoad
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.ViralLoad) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, decimal> WhiteBloodCellCount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.WhiteBloodCellCount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int> NumberOfFingers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.NumberOfFingers) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::LightSwitchApplication.Patient> Patient
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Patient) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::LightSwitchApplication.Patient>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.DateTime DateLabIssued { get; set; }
                new double ViralLoad { get; set; }
                new decimal WhiteBloodCellCount { get; set; }
                new int NumberOfFingers { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Patient { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SpecificLabs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>.Data> c, global::LightSwitchApplication.SpecificLabs.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.SpecificLabs e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.SpecificLabs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.SpecificLabs e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::System.DateTime>.Entry
                    DateLabIssued = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::System.DateTime>.Entry(
                        "DateLabIssued",
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._DateLabIssued_Stub,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._DateLabIssued_ComputeIsReadOnly,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._DateLabIssued_Validate,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._DateLabIssued_GetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._DateLabIssued_SetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._DateLabIssued_OnValueChanged);
                private static void _DateLabIssued_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SpecificLabs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.SpecificLabs.DetailsClass d, object sf)
                {
                    c(d, ref d._DateLabIssued, sf);
                }
                private static bool _DateLabIssued_ComputeIsReadOnly(global::LightSwitchApplication.SpecificLabs e)
                {
                    bool result = false;
                    e.DateLabIssued_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateLabIssued_Validate(global::LightSwitchApplication.SpecificLabs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateLabIssued_Validate(r);
                }
                private static global::System.DateTime _DateLabIssued_GetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d)
                {
                    return d.ImplementationEntity.DateLabIssued;
                }
                private static void _DateLabIssued_SetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateLabIssued = global::LightSwitchApplication.SpecificLabs.DetailsClass.TruncateDate(v);
                }
                private static void _DateLabIssued_OnValueChanged(global::LightSwitchApplication.SpecificLabs e)
                {
                    e.DateLabIssued_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, double>.Entry
                    ViralLoad = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, double>.Entry(
                        "ViralLoad",
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._ViralLoad_Stub,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._ViralLoad_ComputeIsReadOnly,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._ViralLoad_Validate,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._ViralLoad_GetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._ViralLoad_SetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._ViralLoad_OnValueChanged);
                private static void _ViralLoad_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SpecificLabs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, double>.Data> c, global::LightSwitchApplication.SpecificLabs.DetailsClass d, object sf)
                {
                    c(d, ref d._ViralLoad, sf);
                }
                private static bool _ViralLoad_ComputeIsReadOnly(global::LightSwitchApplication.SpecificLabs e)
                {
                    bool result = false;
                    e.ViralLoad_IsReadOnly(ref result);
                    return result;
                }
                private static void _ViralLoad_Validate(global::LightSwitchApplication.SpecificLabs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ViralLoad_Validate(r);
                }
                private static double _ViralLoad_GetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d)
                {
                    return d.ImplementationEntity.ViralLoad;
                }
                private static void _ViralLoad_SetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d, double v)
                {
                    d.ImplementationEntity.ViralLoad = v;
                }
                private static void _ViralLoad_OnValueChanged(global::LightSwitchApplication.SpecificLabs e)
                {
                    e.ViralLoad_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, decimal>.Entry
                    WhiteBloodCellCount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, decimal>.Entry(
                        "WhiteBloodCellCount",
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._WhiteBloodCellCount_Stub,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._WhiteBloodCellCount_ComputeIsReadOnly,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._WhiteBloodCellCount_Validate,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._WhiteBloodCellCount_GetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._WhiteBloodCellCount_SetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._WhiteBloodCellCount_OnValueChanged);
                private static void _WhiteBloodCellCount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SpecificLabs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.SpecificLabs.DetailsClass d, object sf)
                {
                    c(d, ref d._WhiteBloodCellCount, sf);
                }
                private static bool _WhiteBloodCellCount_ComputeIsReadOnly(global::LightSwitchApplication.SpecificLabs e)
                {
                    bool result = false;
                    e.WhiteBloodCellCount_IsReadOnly(ref result);
                    return result;
                }
                private static void _WhiteBloodCellCount_Validate(global::LightSwitchApplication.SpecificLabs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.WhiteBloodCellCount_Validate(r);
                }
                private static decimal _WhiteBloodCellCount_GetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d)
                {
                    return d.ImplementationEntity.WhiteBloodCellCount;
                }
                private static void _WhiteBloodCellCount_SetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.WhiteBloodCellCount = v;
                }
                private static void _WhiteBloodCellCount_OnValueChanged(global::LightSwitchApplication.SpecificLabs e)
                {
                    e.WhiteBloodCellCount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>.Entry
                    NumberOfFingers = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>.Entry(
                        "NumberOfFingers",
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._NumberOfFingers_Stub,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._NumberOfFingers_ComputeIsReadOnly,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._NumberOfFingers_Validate,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._NumberOfFingers_GetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._NumberOfFingers_SetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._NumberOfFingers_OnValueChanged);
                private static void _NumberOfFingers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SpecificLabs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>.Data> c, global::LightSwitchApplication.SpecificLabs.DetailsClass d, object sf)
                {
                    c(d, ref d._NumberOfFingers, sf);
                }
                private static bool _NumberOfFingers_ComputeIsReadOnly(global::LightSwitchApplication.SpecificLabs e)
                {
                    bool result = false;
                    e.NumberOfFingers_IsReadOnly(ref result);
                    return result;
                }
                private static void _NumberOfFingers_Validate(global::LightSwitchApplication.SpecificLabs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NumberOfFingers_Validate(r);
                }
                private static int _NumberOfFingers_GetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d)
                {
                    return d.ImplementationEntity.NumberOfFingers;
                }
                private static void _NumberOfFingers_SetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d, int v)
                {
                    d.ImplementationEntity.NumberOfFingers = v;
                }
                private static void _NumberOfFingers_OnValueChanged(global::LightSwitchApplication.SpecificLabs e)
                {
                    e.NumberOfFingers_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::LightSwitchApplication.Patient>.Entry
                    Patient = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::LightSwitchApplication.Patient>.Entry(
                        "Patient",
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Patient_Stub,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Patient_ComputeIsReadOnly,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Patient_Validate,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Patient_GetCoreImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Patient_GetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Patient_SetImplementationValue,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Patient_Refresh,
                        global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties._Patient_OnValueChanged);
                private static void _Patient_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SpecificLabs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::LightSwitchApplication.Patient>.Data> c, global::LightSwitchApplication.SpecificLabs.DetailsClass d, object sf)
                {
                    c(d, ref d._Patient, sf);
                }
                private static bool _Patient_ComputeIsReadOnly(global::LightSwitchApplication.SpecificLabs e)
                {
                    bool result = false;
                    e.Patient_IsReadOnly(ref result);
                    return result;
                }
                private static void _Patient_Validate(global::LightSwitchApplication.SpecificLabs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Patient_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Patient_GetCoreImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d)
                {
                    return d.ImplementationEntity.Patient;
                }
                private static global::LightSwitchApplication.Patient _Patient_GetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass>(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Patient, ref d._Patient);
                }
                private static void _Patient_SetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass d, global::LightSwitchApplication.Patient v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Patient, ref d._Patient, (i, ev) => i.Patient = ev, v);
                }
                private static void _Patient_Refresh(global::LightSwitchApplication.SpecificLabs.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.SpecificLabs.DetailsClass.PropertySetProperties.Patient, ref d._Patient);
                }
                private static void _Patient_OnValueChanged(global::LightSwitchApplication.SpecificLabs e)
                {
                    e.Patient_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::System.DateTime>.Data _DateLabIssued;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, double>.Data _ViralLoad;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, decimal>.Data _WhiteBloodCellCount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, int>.Data _NumberOfFingers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SpecificLabs, global::LightSwitchApplication.SpecificLabs.DetailsClass, global::LightSwitchApplication.Patient>.Data _Patient;
            
        }
    
        #endregion
    }
    
    #endregion
}
